# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 12 Jun 2016 11:50:44 +0000
*	@ALL	0
start	@ALL	1
wiki:navigation	@ALL	1
wiki:关于wiki:*	@ALL	1
知识管理:技术:*	@user	1
项目:其它项目:ng	@ng	2
