<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: eugene_lijin
 * Date: Tue, 13 Dec 2016 09:04:26 +0000
 */

$conf['title'] = 'LiJin\'s wiki';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['sidebar'] = 'wiki:navigation';
$conf['license'] = '0';
$conf['youarehere'] = 1;
$conf['maxseclevel'] = '5';
$conf['useheading'] = '1';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,register,resendpwd,profile,profile_delete,rss,media,subscribe,unsubscribe,source,export_raw';
$conf['cachetime'] = 60*60*24*5;
$conf['target']['extern'] = '_blank';
$conf['rss_type'] = 'rss2';
$conf['updatecheck'] = 0;
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['proxy']['user'] = 'lijin';
$conf['proxy']['pass'] = '<b>bGlqaW4xMjM=';
$conf['plugin']['indexmenu']['only_admins'] = 1;
$conf['plugin']['indexmenu']['aclcache'] = 'user';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'readable';
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['showHomePageLink'] = 1;
$conf['tpl']['bootstrap3']['showUserHomeLink'] = 0;
$conf['tpl']['bootstrap3']['showIndividualTool'] = 'site';
$conf['tpl']['bootstrap3']['semantic'] = 1;
$conf['tpl']['bootstrap3']['tableStyle'] = 'striped,bordered,hover,condensed,responsive';
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['pageInfo'] = 'date,editor,locked';
$conf['tpl']['bootstrap3']['collapsibleSections'] = 1;
$conf['tpl']['vector']['vector_userpage'] = '0';
$conf['tpl']['vector']['vector_discuss'] = '0';
$conf['tpl']['vector']['vector_sitenotice'] = '0';
$conf['tpl']['vector']['vector_sitenotice_translate'] = '0';
$conf['tpl']['vector']['vector_navigation_translate'] = '0';
$conf['tpl']['vector']['vector_exportbox'] = '0';
$conf['tpl']['vector']['vector_toolbox'] = '0';
$conf['tpl']['vector']['vector_toolbox_default'] = '0';
$conf['tpl']['vector']['vector_qrcodebox'] = '0';
$conf['tpl']['vector']['vector_copyright_translate'] = '0';
$conf['plugin']['discussion']['useavatar'] = '0';

// end auto-generated content
